{% set name = "pipe" %}
{% set version = "2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipe-{{ version }}.tar.gz
  sha256: a1cf3f29f98576b7e6552231142bc711e8dd324513a2c4525fc68c33f47fabad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pipe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JulienPalard/Pipe
  summary: Module enablig a sh like infix syntax (using pipes)
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/JulienPalard/Pipe
  dev_url: https://github.com/JulienPalard/Pipe

extra:
  recipe-maintainers:
    - sugatoray
